import { API_SERVICE_NAME } from '../APIService'
import { DATABASE_SERVICE_NAME } from '../DatabaseService'
import { MQTT_SERVICE_NAME } from '../MqttService'

export const LIST_OF_SERVICES = [
  API_SERVICE_NAME,
  DATABASE_SERVICE_NAME,
  MQTT_SERVICE_NAME
];

export const CODE_EVENT_UNKNOWN = 'UNKNOWN';
export const CODE_EVENT_ACTIVE_DEVICE = 'ACTIVE_DEVICE';
export const CODE_EVENT_UPDATE_SENSOR = 'UPDATE_SENSOR';
export const CODE_EVENT_UPDATE_INPUT = 'UPDATE_INPUT';
export const CODE_EVENT_UPDATE_OUTPUT = 'UPDATE_OUTPUT';
export const CODE_EVENT_SYNC_THRESHOLD = 'SYNC_THRESHOLD';
export const CODE_EVENT_SYNC_GPIO = 'SYNC_GPIO';
export const CODE_EVENT_UPDATE_STATE_DEVICE = 'UPDATE_STATE_DEVICE';
export const CODE_EVENT_REMOVE_DEVICE = 'REMOVE_DEVICE';
