name: Fire Alarm
on:
  push: 
    branches:
      - production
  
jobs:
  build: 
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASS }}
          port: ${{ secrets.SERVER_PORT }} 
          script: |
            cd /miru/server_fire_alarm
            git fetch origin
            git checkout master
            git pull
            yarn build
            pm2 reload server_fire_alarm
