name: Fire Alarm

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Login VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
            host: ${{ secrets.SERVER_HOST }}
            username: ${{ secrets.SERVER_USERNAME }}
            password: ${{ secrets.SERVER_PASS }}
            port: ${{ secrets.SERVER_PORT }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            passphrase: ${{ secrets.SSH_PRIVATE_KEY_PASS }}
            script_stop: true
            script: |
              eval `ssh-agent -s`
              ssh-add ~/.ssh/id_rsa
              git pull
          
